import { GlobalMenu } from "@/components/global-menu";
import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myriadPro = localFont({
  src: [
    {
      path: "../fonts/myriadproregular.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/myriadprobold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  display: "swap",
});

const belyDisplay = localFont({
  src: "../fonts/belydisplayw00regular1.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Glasmuseum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${belyDisplay.className} ${myriadPro.className} `}>
        <Providers>{children}</Providers>
        <GlobalMenu />
      </body>
    </html>
  );
}
